// src/ui.ts
export const K = {
  nav: {
    dashboard: "대시보드",
    inventory: "인벤토리",
    movements: "이동 내역",
    settings: "설정",
  },
  inventory: {
    title: "인벤토리",
    addItem: "품목 추가",
    name: "이름",
    sku: "SKU (선택)",
    barcode: "바코드",
    price: "가격 (선택)",
    initialQty: "초기 수량 (선택)",
    searchPlaceholder: "이름, SKU, 바코드 검색...",
    stock: "재고",
    flags: "상태",
    actions: "작업",
    edit: "수정",
    adjust: "조정",
    delete: "삭제",
    lowStock: "재고 부족",
    expSoon: "유통기한 임박",
    itemAdded: "품목이 추가되었습니다",
  },
  movements: {
    title: "이동 내역",
    type: "유형",
    all: "전체",
    in: "입고",
    out: "출고",
    transfer: "이동",
    search: "검색",
    searchPlaceholder: "품목/사유 검색...",
    date: "일시",
    item: "품목",
    qty: "수량",
    reason: "사유",
    showing: (n: number, t: number) => `총 ${t}건 중 ${n}건 표시`,
  },
};
